spring:
    application:
        name: otel-reservation
    datasource:
        url: "jdbc:postgresql://localhost:5432/otel_reservation"
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: otel_reservation
    flyway:
        baseline-on-migrate: true
        fail-on-missing-locations: true
        schema: ${spring.datasource.hikari.schema}

server:
    port: 9090
    shutdown: graceful

otel:
    reservation:
        api:
            base-path: /otel-reservation/1

